server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: zipkin-sleuth
          uri: https://github.com/JorgeLoya/microservices-tutorial
          search-paths: config-data
  application:
    name: config-service